services:
  - type: web
    name: clarifai-data-cleaning
    env: node
    buildCommand: npm run install-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000